[package]
name = "beyond_client"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.34.0"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["macros", "sync", "rt", "rt-multi-thread"] }
winit = "0.29.10"
